project:
  type: book

book:
  title: "Extensions and Applications of the Tail Pairwise Dependence Matrix"
  author: 
    - name: Matthew Pawley
      url: https://people.bath.ac.uk/mtp34/
      affiliation:
        - name: "University of Bath"
          department: "Department of Mathematical Sciences"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - introduction.qmd
    - background.qmd
    - changing-ext-dep.qmd
    - compositional.qmd
    - eva-data-challenge.qmd
    - shrinkage-tpdm.qmd
    - conclusion.qmd
  appendices:
    - appendix-background.qmd
    - appendix-changing-ext-dep.qmd
    - appendix-compositional.qmd
    - references.qmd
  search:
    location: navbar
    type: overlay

bibliography: phdreferences.bib

execute:
  echo: false

crossref:
  chapters: true

fig-pos: 'h'
fig-width: 8
fig-cap-location: bottom
fig-format: pdf

toc: false
toc-depth: 4

lof: false
lot: false

include-before-body:
  text: |
    \pagenumbering{roman}

pdf-engine: xelatex

format:
  pdf:
    documentclass: scrreprt
    mathspec: true
    template-partials:
      - partials/before-body.tex
    include-before-body: 
      - frontmatter.tex
    include-in-header: 
      - "_macros.tex"
      - text: |
         \usepackage{fancyhdr}
         \usepackage[yyyymmdd,hhmmss]{datetime}
         \usepackage{textcase}
         \pagestyle{fancy}
         \fancyhead[R]{\thepage}
         \fancyhead[L]{\slshape\nouppercase{\leftmark}}
         \fancyfoot[C]{\thepage}
    linestretch: 1.5
    linkcolor: Blue
    urlcolor: Blue
    citecolor: Blue
    geometry:
      - top=25mm
      - left=40mm
      - bottom=25mm
      - right=25mm
    cite-method: biblatex
    biblatexoptions: maxcitenames=2, mincitenames=1, maxbibnames=99, style=authoryear, date=year, doi=false, isbn=false, url=false, eprint=false, uniquename=false, giveninits=true, uniquelist=false
    
editor: source


